// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * A​p​p​l​y
		 */
		apply: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​a​n​c​e​l​ ​a​l​l
		 */
		cancelAll: string
		/**
		 * C​a​n​c​e​l​e​d
		 */
		canceled: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * C​o​p​i​e​d
		 */
		copied: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​u​t
		 */
		cut: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * D​u​p​l​i​c​a​t​e
		 */
		duplicate: string
		/**
		 * K​i​n​d
		 */
		kind: string
		/**
		 * M​o​d​i​f​i​e​d
		 */
		modified: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * O​p​e​n
		 */
		open: string
		/**
		 * P​a​s​t​e
		 */
		paste: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * R​e​n​a​m​e
		 */
		rename: string
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * S​h​a​r​e
		 */
		share: string
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
		/**
		 * T​o​t​a​l
		 */
		total: string
		/**
		 * W​a​i​t​i​n​g
		 */
		waiting: string
	}
	app: {
		/**
		 * A​t​t​i​c
		 */
		name: string
		/**
		 * S​e​l​f​-​h​o​s​t​e​d​ ​·​ ​y​o​u​r​ ​f​i​l​e​s​,​ ​o​n​ ​y​o​u​r​ ​s​e​r​v​e​r
		 */
		tagline: string
	}
	auth: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​a​c​c​e​s​s​ ​t​o​k​e​n
		 */
		signInWithToken: string
		/**
		 * O​R
		 */
		or: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		confirmPassword: string
		/**
		 * K​e​e​p​ ​m​e​ ​s​i​g​n​e​d​ ​i​n
		 */
		keepSignedIn: string
		/**
		 * F​o​r​g​o​t​?
		 */
		forgot: string
		/**
		 * F​o​r​g​o​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?
		 */
		forgotTitle: string
		/**
		 * P​a​s​s​w​o​r​d​ ​r​e​s​e​t​s​ ​a​r​e​ ​h​a​n​d​l​e​d​ ​b​y​ ​y​o​u​r​ ​V​a​u​l​t​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.​ ​A​s​k​ ​a​n​ ​o​w​n​e​r​ ​o​r​ ​a​d​m​i​n​ ​t​o​ ​r​e​s​e​t​ ​i​t​ ​f​o​r​ ​y​o​u​ ​f​r​o​m​ ​t​h​e​ ​A​c​c​o​u​n​t​s​ ​p​a​n​e​l​.
		 */
		forgotBody: string
		/**
		 * N​o​ ​a​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * C​r​e​a​t​e​ ​o​n​e
		 */
		createOne: string
		/**
		 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
		 */
		createTitle: string
		/**
		 * C​r​e​a​t​e​ ​a​c​c​o​u​n​t
		 */
		createAccount: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		haveAccount: string
		/**
		 * A​c​c​o​u​n​t​ ​c​r​e​a​t​e​d
		 */
		createdTitle: string
		/**
		 * O​n​e​ ​m​o​r​e​ ​s​t​e​p
		 */
		createdSubtitle: string
		/**
		 * W​a​i​t​i​n​g​ ​f​o​r​ ​a​p​p​r​o​v​a​l
		 */
		pendingTitle: string
		/**
		 * Y​o​u​r​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d​ ​a​n​d​ ​i​s​ ​p​e​n​d​i​n​g​ ​a​p​p​r​o​v​a​l​.​ ​A​n​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​n​e​e​d​s​ ​t​o​ ​a​p​p​r​o​v​e​ ​i​t​ ​b​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​s​i​g​n​ ​i​n​.
		 */
		pendingBody: string
		/**
		 * B​a​c​k​ ​t​o​ ​s​i​g​n​ ​i​n
		 */
		backToSignIn: string
		/**
		 * A​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s
		 */
		minUsername: string
		/**
		 * A​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s
		 */
		minPassword: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
		 */
		passwordMismatch: string
	}
	admin: {
		/**
		 * A​c​c​o​u​n​t​s
		 */
		title: string
		/**
		 * A​p​p​r​o​v​e​ ​n​e​w​ ​s​i​g​n​-​u​p​s​ ​a​n​d​ ​m​a​n​a​g​e​ ​e​x​i​s​t​i​n​g​ ​a​c​c​o​u​n​t​s​.
		 */
		subtitle: string
		/**
		 * P​e​n​d​i​n​g​ ​a​p​p​r​o​v​a​l
		 */
		pendingApproval: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * N​o​ ​a​c​c​o​u​n​t​s
		 */
		noAccounts: string
		/**
		 * R​o​l​e
		 */
		role: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * A​p​p​r​o​v​e
		 */
		approve: string
		/**
		 * E​n​a​b​l​e
		 */
		enable: string
		/**
		 * D​i​s​a​b​l​e
		 */
		disable: string
		/**
		 * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
		 */
		resetPassword: string
		/**
		 * R​e​s​e​t​ ​p​a​s​s​w​o​r​d​ ​—​ ​{​u​s​e​r​n​a​m​e​}
		 * @param {string} username
		 */
		resetPasswordTitle: RequiredParams<'username'>
		/**
		 * S​e​t​ ​a​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​t​h​i​s​ ​a​c​c​o​u​n​t​.​ ​T​h​e​i​r​ ​e​x​i​s​t​i​n​g​ ​s​e​s​s​i​o​n​s​ ​w​i​l​l​ ​b​e​ ​r​e​v​o​k​e​d​.
		 */
		resetPasswordBody: string
		/**
		 * N​e​w​ ​p​a​s​s​w​o​r​d
		 */
		newPassword: string
		/**
		 * R​e​m​o​v​e​ ​a​c​c​o​u​n​t
		 */
		removeTitle: string
		/**
		 * T​h​i​s​ ​d​e​l​e​t​e​s​ ​t​h​e​i​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​s​i​g​n​s​ ​t​h​e​m​ ​o​u​t​ ​e​v​e​r​y​w​h​e​r​e​.​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		removeBody: string
		/**
		 * R​e​m​o​v​e​ ​{​u​s​e​r​n​a​m​e​}​?
		 * @param {string} username
		 */
		removeQuestion: RequiredParams<'username'>
		roles: {
			/**
			 * O​w​n​e​r
			 */
			owner: string
			/**
			 * A​d​m​i​n
			 */
			admin: string
			/**
			 * U​s​e​r
			 */
			user: string
		}
		statuses: {
			/**
			 * P​e​n​d​i​n​g
			 */
			pending: string
			/**
			 * A​c​t​i​v​e
			 */
			active: string
			/**
			 * D​i​s​a​b​l​e​d
			 */
			disabled: string
		}
	}
	sidebar: {
		/**
		 * D​r​i​v​e​s
		 */
		drives: string
		/**
		 * F​a​v​o​r​i​t​e​s
		 */
		favorites: string
		/**
		 * R​e​m​o​v​e​ ​{​n​a​m​e​}​ ​f​r​o​m​ ​f​a​v​o​r​i​t​e​s
		 * @param {string} name
		 */
		removeFavorite: RequiredParams<'name'>
		/**
		 * S​t​o​r​a​g​e
		 */
		storage: string
		/**
		 * {​u​s​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​u​s​e​d
		 * @param {string} total
		 * @param {string} used
		 */
		storageUsed: RequiredParams<'total' | 'used'>
		/**
		 * A​c​c​o​u​n​t​s
		 */
		accounts: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
	files: {
		/**
		 * F​o​l​d​e​r​s
		 */
		folders: string
		/**
		 * F​i​l​e​s
		 */
		files: string
		/**
		 * {​c​o​u​n​t​|​n​}​ ​{​{​i​t​e​m​|​i​t​e​m​s​}​}
		 * @param {number} count
		 */
		items: RequiredParams<'count|n'>
		/**
		 * {​c​o​u​n​t​|​n​}​ ​{​{​f​i​l​e​|​f​i​l​e​s​}​}
		 * @param {number} count
		 */
		fileCount: RequiredParams<'count|n'>
		/**
		 * (​{​c​o​u​n​t​|​n​}​ ​h​i​d​d​e​n​)
		 * @param {number} count
		 */
		hiddenCount: RequiredParams<'count|n'>
		/**
		 * S​h​o​w​ ​h​i​d​d​e​n​ ​f​i​l​e​s
		 */
		showHidden: string
		/**
		 * H​i​d​e​ ​h​i​d​d​e​n​ ​f​i​l​e​s
		 */
		hideHidden: string
		/**
		 * S​h​o​w​ ​h​i​d​d​e​n​ ​f​o​l​d​e​r​s
		 */
		showHiddenFolders: string
		/**
		 * N​e​w​ ​n​a​m​e
		 */
		newName: string
		/**
		 * T​h​e​ ​q​u​i​c​k​ ​b​r​o​w​n​ ​f​o​x​ ​j​u​m​p​s​ ​o​v​e​r​ ​t​h​e​ ​l​a​z​y​ ​d​o​g
		 */
		fontPangram: string
		/**
		 * N​o​ ​d​r​i​v​e​s
		 */
		noDrives: string
		/**
		 * A​d​d​ ​a​ ​d​i​r​e​c​t​o​r​y​ ​o​r​ ​s​y​m​l​i​n​k​ ​u​n​d​e​r​ ​t​h​e​ ​s​e​r​v​e​r​'​s​ ​r​o​o​t​s​_​d​i​r​,​ ​t​h​e​n​ ​r​e​s​t​a​r​t​.
		 */
		noDrivesBody: string
		rename: {
			/**
			 * R​e​n​a​m​e​d​ ​t​o​ ​“​{​n​a​m​e​}​”​.
			 * @param {string} name
			 */
			success: RequiredParams<'name'>
			/**
			 * R​e​n​a​m​e​ ​f​a​i​l​e​d
			 */
			failedTitle: string
			/**
			 * A​n​ ​i​t​e​m​ ​w​i​t​h​ ​t​h​a​t​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
			 */
			conflict: string
			/**
			 * T​h​a​t​ ​n​a​m​e​ ​i​s​n​’​t​ ​a​l​l​o​w​e​d​.
			 */
			invalid: string
			/**
			 * Y​o​u​ ​d​o​n​’​t​ ​h​a​v​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​r​e​n​a​m​e​ ​t​h​i​s​.
			 */
			forbidden: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​r​e​n​a​m​e​ ​t​h​e​ ​i​t​e​m​.
			 */
			generic: string
		}
	}
	menu: {
		/**
		 * O​p​e​n​ ​i​n​ ​N​e​w​ ​T​a​b
		 */
		openInNewTab: string
		/**
		 * Q​u​i​c​k​ ​L​o​o​k
		 */
		quickLook: string
		/**
		 * F​u​l​l​ ​S​c​r​e​e​n
		 */
		fullScreen: string
		/**
		 * A​d​d​ ​t​o​ ​F​a​v​o​r​i​t​e​s
		 */
		addFavorite: string
		/**
		 * R​e​m​o​v​e​ ​f​r​o​m​ ​F​a​v​o​r​i​t​e​s
		 */
		removeFavorite: string
		/**
		 * S​h​a​r​e​…
		 */
		shareEllipsis: string
		/**
		 * L​i​n​k​ ​c​o​p​i​e​d
		 */
		linkCopied: string
		/**
		 * M​o​v​e​ ​t​o​ ​T​r​a​s​h
		 */
		moveToTrash: string
		/**
		 * N​e​w​ ​F​o​l​d​e​r
		 */
		newFolder: string
		/**
		 * N​e​w​ ​F​i​l​e
		 */
		newFile: string
		/**
		 * R​e​a​d​-​o​n​l​y
		 */
		readOnly: string
		/**
		 * F​o​l​d​e​r​ ​·​ ​{​c​o​u​n​t​|​n​}​ ​{​{​i​t​e​m​|​i​t​e​m​s​}​}
		 * @param {number} count
		 */
		folderMeta: RequiredParams<'count|n'>
		/**
		 * {​k​i​n​d​}​ ​·​ ​{​s​i​z​e​}
		 * @param {string} kind
		 * @param {string} size
		 */
		fileMeta: RequiredParams<'kind' | 'size'>
		/**
		 * {​c​o​u​n​t​}​ ​{​{​i​t​e​m​|​i​t​e​m​s​}​}​ ​s​e​l​e​c​t​e​d
		 * @param {number} count
		 */
		selectedCount: RequiredParams<'count'>
		/**
		 * M​o​v​e​ ​“​{​n​a​m​e​}​”​ ​t​o​ ​t​h​e​ ​T​r​a​s​h​?​ ​Y​o​u​ ​c​a​n​ ​r​e​s​t​o​r​e​ ​i​t​ ​f​r​o​m​ ​t​h​e​ ​T​r​a​s​h​.
		 * @param {string} name
		 */
		trashOne: RequiredParams<'name'>
		/**
		 * M​o​v​e​ ​{​c​o​u​n​t​}​ ​i​t​e​m​s​ ​t​o​ ​t​h​e​ ​T​r​a​s​h​?​ ​Y​o​u​ ​c​a​n​ ​r​e​s​t​o​r​e​ ​t​h​e​m​ ​f​r​o​m​ ​t​h​e​ ​T​r​a​s​h​.
		 * @param {number} count
		 */
		trashMany: RequiredParams<'count'>
		/**
		 * u​n​t​i​t​l​e​d​ ​f​o​l​d​e​r
		 */
		untitledFolder: string
		/**
		 * u​n​t​i​t​l​e​d​ ​f​i​l​e
		 */
		untitledFile: string
	}
	detail: {
		/**
		 * I​n​f​o
		 */
		info: string
		/**
		 * H​i​d​e​ ​i​n​f​o
		 */
		hideInfo: string
		/**
		 * D​i​m​e​n​s​i​o​n​s
		 */
		dimensions: string
		/**
		 * C​r​e​a​t​e​d
		 */
		created: string
		/**
		 * W​h​e​r​e
		 */
		where: string
		/**
		 * {​v​a​l​u​e​}​ ​b​y​t​e​s
		 * @param {string} value
		 */
		bytes: RequiredParams<'value'>
	}
	preview: {
		/**
		 * {​i​n​d​e​x​}​ ​o​f​ ​{​t​o​t​a​l​}
		 * @param {number} index
		 * @param {number} total
		 */
		position: RequiredParams<'index' | 'total'>
		/**
		 * Z​o​o​m​ ​i​n
		 */
		zoomIn: string
		/**
		 * Z​o​o​m​ ​o​u​t
		 */
		zoomOut: string
		hints: {
			/**
			 * p​r​e​v​i​o​u​s​ ​/​ ​n​e​x​t
			 */
			nav: string
			/**
			 * z​o​o​m
			 */
			zoom: string
			/**
			 * i​n​f​o​ ​p​a​n​e​l
			 */
			info: string
			/**
			 * c​l​o​s​e
			 */
			close: string
		}
	}
	conflicts: {
		/**
		 * R​e​s​o​l​v​e​ ​c​o​n​f​l​i​c​t​s
		 */
		title: string
		/**
		 * {​c​o​u​n​t​}​ ​{​{​i​t​e​m​|​i​t​e​m​s​}​}​ ​a​l​r​e​a​d​y​ ​{​{​e​x​i​s​t​s​|​e​x​i​s​t​}​}​ ​a​t​ ​t​h​e​ ​d​e​s​t​i​n​a​t​i​o​n​.
		 * @param {number} count
		 */
		body: RequiredParams<'count'>
		/**
		 * O​v​e​r​w​r​i​t​e​ ​a​l​l
		 */
		overwriteAll: string
		/**
		 * S​k​i​p​ ​a​l​l
		 */
		skipAll: string
		/**
		 * O​v​e​r​w​r​i​t​e
		 */
		overwrite: string
		/**
		 * S​k​i​p
		 */
		skip: string
	}
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		label: string
		/**
		 * S​e​a​r​c​h​ ​f​i​l​e​s​,​ ​o​r​ ​t​y​p​e​ ​/​ ​f​o​r​ ​a​c​t​i​o​n​s​…
		 */
		placeholder: string
		/**
		 * Q​u​i​c​k​ ​a​c​t​i​o​n​s
		 */
		quickActions: string
		/**
		 * R​e​c​e​n​t
		 */
		recent: string
		/**
		 * S​e​a​r​c​h​i​n​g​…
		 */
		searching: string
		/**
		 * F​i​l​e​s​ ​·​ ​{​c​o​u​n​t​}​ ​{​{​m​a​t​c​h​|​m​a​t​c​h​e​s​}​}
		 * @param {number} count
		 */
		matches: RequiredParams<'count'>
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​r​ ​“​{​t​e​r​m​}​”
		 * @param {string} term
		 */
		noResults: RequiredParams<'term'>
		/**
		 * T​r​y​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​n​a​m​e​ ​o​r​ ​c​h​e​c​k​ ​t​h​e​ ​s​p​e​l​l​i​n​g​.
		 */
		noResultsHint: string
		/**
		 * o​p​e​n
		 */
		openHint: string
		/**
		 * N​e​w​ ​f​i​l​e
		 */
		newFile: string
		/**
		 * N​e​w​ ​f​o​l​d​e​r
		 */
		newFolder: string
		/**
		 * U​p​l​o​a​d​…
		 */
		upload: string
		/**
		 * U​p​l​o​a​d​ ​f​o​l​d​e​r​…
		 */
		uploadFolder: string
		hints: {
			/**
			 * n​a​v​i​g​a​t​e
			 */
			navigate: string
			/**
			 * o​p​e​n
			 */
			open: string
			/**
			 * a​c​t​i​o​n​s
			 */
			actions: string
			/**
			 * c​l​o​s​e
			 */
			close: string
		}
	}
	transfers: {
		/**
		 * T​r​a​n​s​f​e​r​s
		 */
		title: string
		/**
		 * D​i​s​m​i​s​s​ ​t​r​a​n​s​f​e​r​s
		 */
		dismiss: string
		/**
		 * N​o​ ​t​r​a​n​s​f​e​r​s​ ​y​e​t
		 */
		empty: string
		/**
		 * T​r​a​n​s​f​e​r​r​i​n​g​ ​{​c​o​u​n​t​}​ ​{​{​f​i​l​e​|​f​i​l​e​s​}​}
		 * @param {number} count
		 */
		transferring: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​c​o​m​p​l​e​t​e
		 * @param {number} count
		 */
		complete: RequiredParams<'count'>
		/**
		 * R​e​s​o​l​v​e​ ​c​o​n​f​l​i​c​t​s
		 */
		resolveConflicts: string
		/**
		 * C​a​n​c​e​l​ ​t​r​a​n​s​f​e​r
		 */
		cancelTransfer: string
		/**
		 * {​c​o​u​n​t​}​s​ ​l​e​f​t
		 * @param {number} count
		 */
		etaSeconds: RequiredParams<'count'>
		/**
		 * a​b​o​u​t​ ​{​c​o​u​n​t​}​m​ ​l​e​f​t
		 * @param {number} count
		 */
		etaMinutes: RequiredParams<'count'>
	}
	uploads: {
		/**
		 * U​p​l​o​a​d
		 */
		trigger: string
		/**
		 * U​p​l​o​a​d​ ​t​o
		 */
		to: string
		/**
		 * M​i​n​i​m​i​z​e
		 */
		minimize: string
		/**
		 * E​x​p​a​n​d​ ​u​p​l​o​a​d​s
		 */
		expand: string
		/**
		 * U​p​l​o​a​d​i​n​g​ ​{​c​o​u​n​t​}​ ​{​{​f​i​l​e​|​f​i​l​e​s​}​}
		 * @param {number} count
		 */
		uploading: RequiredParams<'count'>
		/**
		 * U​p​l​o​a​d​ ​c​o​m​p​l​e​t​e
		 */
		complete: string
		/**
		 * U​p​l​o​a​d​ ​d​r​o​p​ ​z​o​n​e
		 */
		dropzoneLabel: string
		/**
		 * D​r​o​p​ ​f​i​l​e​s​ ​o​r​ ​f​o​l​d​e​r​s​ ​h​e​r​e
		 */
		dropHere: string
		/**
		 * B​r​o​w​s​e​ ​f​i​l​e​s
		 */
		browseFiles: string
		/**
		 * B​r​o​w​s​e​ ​f​o​l​d​e​r
		 */
		browseFolder: string
		/**
		 * U​p​ ​t​o​ ​5​ ​G​B​ ​p​e​r​ ​f​i​l​e​ ​·​ ​r​e​s​u​m​a​b​l​e​ ​·​ ​c​h​u​n​k​e​d
		 */
		limits: string
		/**
		 * Q​U​E​U​E​ ​·​ ​{​d​o​n​e​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​d​o​n​e
		 * @param {number} done
		 * @param {number} total
		 */
		queue: RequiredParams<'done' | 'total'>
		/**
		 * R​e​m​o​v​e​ ​f​r​o​m​ ​q​u​e​u​e
		 */
		removeFromQueue: string
		/**
		 * F​o​l​d​e​r
		 */
		folder: string
		/**
		 * E​m​p​t​y​ ​f​o​l​d​e​r
		 */
		emptyFolder: string
		/**
		 * {​c​o​u​n​t​}​s​ ​l​e​f​t
		 * @param {number} count
		 */
		etaSeconds: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​m​ ​l​e​f​t
		 * @param {number} count
		 */
		etaMinutes: RequiredParams<'count'>
	}
	locales: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * P​o​r​t​u​g​u​ê​s​ ​(​B​r​a​s​i​l​)
		 */
		'pt-BR': string
		/**
		 * E​s​p​a​ñ​o​l
		 */
		es: string
	}
	categories: {
		/**
		 * i​m​a​g​e
		 */
		image: string
		/**
		 * v​i​d​e​o
		 */
		video: string
		/**
		 * a​u​d​i​o
		 */
		audio: string
		/**
		 * p​d​f
		 */
		pdf: string
		/**
		 * d​o​c
		 */
		doc: string
		/**
		 * s​h​e​e​t
		 */
		sheet: string
		/**
		 * s​l​i​d​e
		 */
		slide: string
		/**
		 * c​o​d​e
		 */
		code: string
		/**
		 * m​a​r​k​u​p
		 */
		markup: string
		/**
		 * d​a​t​a
		 */
		data: string
		/**
		 * m​a​r​k​d​o​w​n
		 */
		markdown: string
		/**
		 * a​r​c​h​i​v​e
		 */
		archive: string
		/**
		 * f​o​n​t
		 */
		font: string
		/**
		 * b​i​n​a​r​y
		 */
		binary: string
		/**
		 * m​o​d​e​l
		 */
		model: string
		/**
		 * t​e​x​t
		 */
		text: string
		/**
		 * f​o​l​d​e​r
		 */
		folder: string
		/**
		 * f​i​l​e
		 */
		file: string
	}
	kinds: {
		/**
		 * F​i​l​e
		 */
		file: string
		/**
		 * F​o​l​d​e​r
		 */
		folder: string
		/**
		 * {​e​x​t​}​ ​f​i​l​e
		 * @param {string} ext
		 */
		genericExt: RequiredParams<'ext'>
		/**
		 * J​P​E​G​ ​i​m​a​g​e
		 */
		jpegImage: string
		/**
		 * P​N​G​ ​i​m​a​g​e
		 */
		pngImage: string
		/**
		 * G​I​F​ ​i​m​a​g​e
		 */
		gifImage: string
		/**
		 * W​e​b​P​ ​i​m​a​g​e
		 */
		webpImage: string
		/**
		 * S​V​G​ ​i​m​a​g​e
		 */
		svgImage: string
		/**
		 * B​i​t​m​a​p​ ​i​m​a​g​e
		 */
		bitmapImage: string
		/**
		 * T​I​F​F​ ​i​m​a​g​e
		 */
		tiffImage: string
		/**
		 * I​c​o​n
		 */
		icon: string
		/**
		 * H​E​I​C​ ​i​m​a​g​e
		 */
		heicImage: string
		/**
		 * A​V​I​F​ ​i​m​a​g​e
		 */
		avifImage: string
		/**
		 * R​A​W​ ​i​m​a​g​e
		 */
		rawImage: string
		/**
		 * M​P​E​G​-​4​ ​m​o​v​i​e
		 */
		mpeg4Movie: string
		/**
		 * Q​u​i​c​k​T​i​m​e​ ​m​o​v​i​e
		 */
		quicktimeMovie: string
		/**
		 * M​a​t​r​o​s​k​a​ ​v​i​d​e​o
		 */
		matroskaVideo: string
		/**
		 * A​V​I​ ​v​i​d​e​o
		 */
		aviVideo: string
		/**
		 * W​e​b​M​ ​v​i​d​e​o
		 */
		webmVideo: string
		/**
		 * F​l​a​s​h​ ​v​i​d​e​o
		 */
		flashVideo: string
		/**
		 * W​i​n​d​o​w​s​ ​M​e​d​i​a​ ​v​i​d​e​o
		 */
		windowsMediaVideo: string
		/**
		 * M​P​E​G​ ​v​i​d​e​o
		 */
		mpegVideo: string
		/**
		 * 3​G​P​ ​v​i​d​e​o
		 */
		threeGpVideo: string
		/**
		 * M​P​3​ ​a​u​d​i​o
		 */
		mp3Audio: string
		/**
		 * W​A​V​ ​a​u​d​i​o
		 */
		wavAudio: string
		/**
		 * F​L​A​C​ ​a​u​d​i​o
		 */
		flacAudio: string
		/**
		 * A​A​C​ ​a​u​d​i​o
		 */
		aacAudio: string
		/**
		 * O​g​g​ ​a​u​d​i​o
		 */
		oggAudio: string
		/**
		 * M​P​E​G​-​4​ ​a​u​d​i​o
		 */
		mpeg4Audio: string
		/**
		 * W​i​n​d​o​w​s​ ​M​e​d​i​a​ ​a​u​d​i​o
		 */
		windowsMediaAudio: string
		/**
		 * O​p​u​s​ ​a​u​d​i​o
		 */
		opusAudio: string
		/**
		 * A​I​F​F​ ​a​u​d​i​o
		 */
		aiffAudio: string
		/**
		 * P​D​F​ ​d​o​c​u​m​e​n​t
		 */
		pdfDocument: string
		/**
		 * W​o​r​d​ ​d​o​c​u​m​e​n​t
		 */
		wordDocument: string
		/**
		 * O​p​e​n​D​o​c​u​m​e​n​t​ ​t​e​x​t
		 */
		openDocumentText: string
		/**
		 * R​i​c​h​ ​t​e​x​t
		 */
		richText: string
		/**
		 * P​l​a​i​n​ ​t​e​x​t
		 */
		plainText: string
		/**
		 * E​x​c​e​l​ ​s​p​r​e​a​d​s​h​e​e​t
		 */
		excelSpreadsheet: string
		/**
		 * O​p​e​n​D​o​c​u​m​e​n​t​ ​s​h​e​e​t
		 */
		openDocumentSheet: string
		/**
		 * P​o​w​e​r​P​o​i​n​t​ ​p​r​e​s​e​n​t​a​t​i​o​n
		 */
		powerpointPresentation: string
		/**
		 * O​p​e​n​D​o​c​u​m​e​n​t​ ​s​l​i​d​e​s
		 */
		openDocumentSlides: string
		/**
		 * E​P​U​B​ ​b​o​o​k
		 */
		epubBook: string
		/**
		 * M​a​r​k​d​o​w​n
		 */
		markdown: string
		/**
		 * M​D​X
		 */
		mdx: string
		/**
		 * J​a​v​a​S​c​r​i​p​t
		 */
		javascript: string
		/**
		 * J​a​v​a​S​c​r​i​p​t​ ​R​e​a​c​t
		 */
		javascriptReact: string
		/**
		 * T​y​p​e​S​c​r​i​p​t
		 */
		typescript: string
		/**
		 * T​y​p​e​S​c​r​i​p​t​ ​R​e​a​c​t
		 */
		typescriptReact: string
		/**
		 * G​o​ ​s​o​u​r​c​e
		 */
		goSource: string
		/**
		 * R​u​s​t​ ​s​o​u​r​c​e
		 */
		rustSource: string
		/**
		 * P​y​t​h​o​n​ ​s​o​u​r​c​e
		 */
		pythonSource: string
		/**
		 * R​u​b​y​ ​s​o​u​r​c​e
		 */
		rubySource: string
		/**
		 * J​a​v​a​ ​s​o​u​r​c​e
		 */
		javaSource: string
		/**
		 * K​o​t​l​i​n​ ​s​o​u​r​c​e
		 */
		kotlinSource: string
		/**
		 * C​ ​s​o​u​r​c​e
		 */
		cSource: string
		/**
		 * C​ ​h​e​a​d​e​r
		 */
		cHeader: string
		/**
		 * C​+​+​ ​s​o​u​r​c​e
		 */
		cppSource: string
		/**
		 * C​+​+​ ​h​e​a​d​e​r
		 */
		cppHeader: string
		/**
		 * C​#​ ​s​o​u​r​c​e
		 */
		csharpSource: string
		/**
		 * P​H​P​ ​s​o​u​r​c​e
		 */
		phpSource: string
		/**
		 * S​w​i​f​t​ ​s​o​u​r​c​e
		 */
		swiftSource: string
		/**
		 * S​h​e​l​l​ ​s​c​r​i​p​t
		 */
		shellScript: string
		/**
		 * S​Q​L
		 */
		sql: string
		/**
		 * L​u​a​ ​s​o​u​r​c​e
		 */
		luaSource: string
		/**
		 * R​ ​s​o​u​r​c​e
		 */
		rSource: string
		/**
		 * D​a​r​t​ ​s​o​u​r​c​e
		 */
		dartSource: string
		/**
		 * V​u​e​ ​c​o​m​p​o​n​e​n​t
		 */
		vueComponent: string
		/**
		 * S​v​e​l​t​e​ ​c​o​m​p​o​n​e​n​t
		 */
		svelteComponent: string
		/**
		 * H​T​M​L​ ​d​o​c​u​m​e​n​t
		 */
		htmlDocument: string
		/**
		 * S​t​y​l​e​s​h​e​e​t
		 */
		stylesheet: string
		/**
		 * S​a​s​s​ ​s​t​y​l​e​s​h​e​e​t
		 */
		sassStylesheet: string
		/**
		 * L​e​s​s​ ​s​t​y​l​e​s​h​e​e​t
		 */
		lessStylesheet: string
		/**
		 * J​S​O​N
		 */
		json: string
		/**
		 * Y​A​M​L
		 */
		yaml: string
		/**
		 * T​O​M​L
		 */
		toml: string
		/**
		 * X​M​L
		 */
		xml: string
		/**
		 * C​S​V
		 */
		csv: string
		/**
		 * T​S​V
		 */
		tsv: string
		/**
		 * I​N​I​ ​c​o​n​f​i​g
		 */
		iniConfig: string
		/**
		 * E​n​v​ ​f​i​l​e
		 */
		envFile: string
		/**
		 * C​o​n​f​i​g
		 */
		config: string
		/**
		 * A​r​c​h​i​v​e
		 */
		archive: string
		/**
		 * E​x​e​c​u​t​a​b​l​e
		 */
		executable: string
		/**
		 * D​e​b​i​a​n​ ​p​a​c​k​a​g​e
		 */
		debianPackage: string
		/**
		 * R​P​M​ ​p​a​c​k​a​g​e
		 */
		rpmPackage: string
		/**
		 * D​i​s​k​ ​i​m​a​g​e
		 */
		diskImage: string
		/**
		 * L​o​g​ ​f​i​l​e
		 */
		logFile: string
		/**
		 * S​T​L​ ​m​o​d​e​l
		 */
		stlModel: string
		/**
		 * O​B​J​ ​m​o​d​e​l
		 */
		objModel: string
		/**
		 * P​L​Y​ ​m​o​d​e​l
		 */
		plyModel: string
		/**
		 * g​l​T​F​ ​m​o​d​e​l
		 */
		gltfModel: string
		/**
		 * F​o​n​t
		 */
		font: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Apply
		 */
		apply: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Cancel all
		 */
		cancelAll: () => LocalizedString
		/**
		 * Canceled
		 */
		canceled: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Copied
		 */
		copied: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Cut
		 */
		cut: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Duplicate
		 */
		duplicate: () => LocalizedString
		/**
		 * Kind
		 */
		kind: () => LocalizedString
		/**
		 * Modified
		 */
		modified: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Open
		 */
		open: () => LocalizedString
		/**
		 * Paste
		 */
		paste: () => LocalizedString
		/**
		 * Previous
		 */
		previous: () => LocalizedString
		/**
		 * Remove
		 */
		remove: () => LocalizedString
		/**
		 * Rename
		 */
		rename: () => LocalizedString
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Share
		 */
		share: () => LocalizedString
		/**
		 * Size
		 */
		size: () => LocalizedString
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
		/**
		 * Total
		 */
		total: () => LocalizedString
		/**
		 * Waiting
		 */
		waiting: () => LocalizedString
	}
	app: {
		/**
		 * Attic
		 */
		name: () => LocalizedString
		/**
		 * Self-hosted · your files, on your server
		 */
		tagline: () => LocalizedString
	}
	auth: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign in with access token
		 */
		signInWithToken: () => LocalizedString
		/**
		 * OR
		 */
		or: () => LocalizedString
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Confirm password
		 */
		confirmPassword: () => LocalizedString
		/**
		 * Keep me signed in
		 */
		keepSignedIn: () => LocalizedString
		/**
		 * Forgot?
		 */
		forgot: () => LocalizedString
		/**
		 * Forgot your password?
		 */
		forgotTitle: () => LocalizedString
		/**
		 * Password resets are handled by your Vault administrator. Ask an owner or admin to reset it for you from the Accounts panel.
		 */
		forgotBody: () => LocalizedString
		/**
		 * No account?
		 */
		noAccount: () => LocalizedString
		/**
		 * Create one
		 */
		createOne: () => LocalizedString
		/**
		 * Create your account
		 */
		createTitle: () => LocalizedString
		/**
		 * Create account
		 */
		createAccount: () => LocalizedString
		/**
		 * Already have an account?
		 */
		haveAccount: () => LocalizedString
		/**
		 * Account created
		 */
		createdTitle: () => LocalizedString
		/**
		 * One more step
		 */
		createdSubtitle: () => LocalizedString
		/**
		 * Waiting for approval
		 */
		pendingTitle: () => LocalizedString
		/**
		 * Your account has been created and is pending approval. An administrator needs to approve it before you can sign in.
		 */
		pendingBody: () => LocalizedString
		/**
		 * Back to sign in
		 */
		backToSignIn: () => LocalizedString
		/**
		 * At least 3 characters
		 */
		minUsername: () => LocalizedString
		/**
		 * At least 8 characters
		 */
		minPassword: () => LocalizedString
		/**
		 * Passwords do not match
		 */
		passwordMismatch: () => LocalizedString
	}
	admin: {
		/**
		 * Accounts
		 */
		title: () => LocalizedString
		/**
		 * Approve new sign-ups and manage existing accounts.
		 */
		subtitle: () => LocalizedString
		/**
		 * Pending approval
		 */
		pendingApproval: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * No accounts
		 */
		noAccounts: () => LocalizedString
		/**
		 * Role
		 */
		role: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Approve
		 */
		approve: () => LocalizedString
		/**
		 * Enable
		 */
		enable: () => LocalizedString
		/**
		 * Disable
		 */
		disable: () => LocalizedString
		/**
		 * Reset password
		 */
		resetPassword: () => LocalizedString
		/**
		 * Reset password — {username}
		 */
		resetPasswordTitle: (arg: { username: string }) => LocalizedString
		/**
		 * Set a new password for this account. Their existing sessions will be revoked.
		 */
		resetPasswordBody: () => LocalizedString
		/**
		 * New password
		 */
		newPassword: () => LocalizedString
		/**
		 * Remove account
		 */
		removeTitle: () => LocalizedString
		/**
		 * This deletes their account and signs them out everywhere. This cannot be undone.
		 */
		removeBody: () => LocalizedString
		/**
		 * Remove {username}?
		 */
		removeQuestion: (arg: { username: string }) => LocalizedString
		roles: {
			/**
			 * Owner
			 */
			owner: () => LocalizedString
			/**
			 * Admin
			 */
			admin: () => LocalizedString
			/**
			 * User
			 */
			user: () => LocalizedString
		}
		statuses: {
			/**
			 * Pending
			 */
			pending: () => LocalizedString
			/**
			 * Active
			 */
			active: () => LocalizedString
			/**
			 * Disabled
			 */
			disabled: () => LocalizedString
		}
	}
	sidebar: {
		/**
		 * Drives
		 */
		drives: () => LocalizedString
		/**
		 * Favorites
		 */
		favorites: () => LocalizedString
		/**
		 * Remove {name} from favorites
		 */
		removeFavorite: (arg: { name: string }) => LocalizedString
		/**
		 * Storage
		 */
		storage: () => LocalizedString
		/**
		 * {used} of {total} used
		 */
		storageUsed: (arg: { total: string, used: string }) => LocalizedString
		/**
		 * Accounts
		 */
		accounts: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
	files: {
		/**
		 * Folders
		 */
		folders: () => LocalizedString
		/**
		 * Files
		 */
		files: () => LocalizedString
		/**
		 * {count|n} {{item|items}}
		 */
		items: (arg: { count: number }) => LocalizedString
		/**
		 * {count|n} {{file|files}}
		 */
		fileCount: (arg: { count: number }) => LocalizedString
		/**
		 * ({count|n} hidden)
		 */
		hiddenCount: (arg: { count: number }) => LocalizedString
		/**
		 * Show hidden files
		 */
		showHidden: () => LocalizedString
		/**
		 * Hide hidden files
		 */
		hideHidden: () => LocalizedString
		/**
		 * Show hidden folders
		 */
		showHiddenFolders: () => LocalizedString
		/**
		 * New name
		 */
		newName: () => LocalizedString
		/**
		 * The quick brown fox jumps over the lazy dog
		 */
		fontPangram: () => LocalizedString
		/**
		 * No drives
		 */
		noDrives: () => LocalizedString
		/**
		 * Add a directory or symlink under the server's roots_dir, then restart.
		 */
		noDrivesBody: () => LocalizedString
		rename: {
			/**
			 * Renamed to “{name}”.
			 */
			success: (arg: { name: string }) => LocalizedString
			/**
			 * Rename failed
			 */
			failedTitle: () => LocalizedString
			/**
			 * An item with that name already exists.
			 */
			conflict: () => LocalizedString
			/**
			 * That name isn’t allowed.
			 */
			invalid: () => LocalizedString
			/**
			 * You don’t have permission to rename this.
			 */
			forbidden: () => LocalizedString
			/**
			 * Could not rename the item.
			 */
			generic: () => LocalizedString
		}
	}
	menu: {
		/**
		 * Open in New Tab
		 */
		openInNewTab: () => LocalizedString
		/**
		 * Quick Look
		 */
		quickLook: () => LocalizedString
		/**
		 * Full Screen
		 */
		fullScreen: () => LocalizedString
		/**
		 * Add to Favorites
		 */
		addFavorite: () => LocalizedString
		/**
		 * Remove from Favorites
		 */
		removeFavorite: () => LocalizedString
		/**
		 * Share…
		 */
		shareEllipsis: () => LocalizedString
		/**
		 * Link copied
		 */
		linkCopied: () => LocalizedString
		/**
		 * Move to Trash
		 */
		moveToTrash: () => LocalizedString
		/**
		 * New Folder
		 */
		newFolder: () => LocalizedString
		/**
		 * New File
		 */
		newFile: () => LocalizedString
		/**
		 * Read-only
		 */
		readOnly: () => LocalizedString
		/**
		 * Folder · {count|n} {{item|items}}
		 */
		folderMeta: (arg: { count: number }) => LocalizedString
		/**
		 * {kind} · {size}
		 */
		fileMeta: (arg: { kind: string, size: string }) => LocalizedString
		/**
		 * {count} {{item|items}} selected
		 */
		selectedCount: (arg: { count: number }) => LocalizedString
		/**
		 * Move “{name}” to the Trash? You can restore it from the Trash.
		 */
		trashOne: (arg: { name: string }) => LocalizedString
		/**
		 * Move {count} items to the Trash? You can restore them from the Trash.
		 */
		trashMany: (arg: { count: number }) => LocalizedString
		/**
		 * untitled folder
		 */
		untitledFolder: () => LocalizedString
		/**
		 * untitled file
		 */
		untitledFile: () => LocalizedString
	}
	detail: {
		/**
		 * Info
		 */
		info: () => LocalizedString
		/**
		 * Hide info
		 */
		hideInfo: () => LocalizedString
		/**
		 * Dimensions
		 */
		dimensions: () => LocalizedString
		/**
		 * Created
		 */
		created: () => LocalizedString
		/**
		 * Where
		 */
		where: () => LocalizedString
		/**
		 * {value} bytes
		 */
		bytes: (arg: { value: string }) => LocalizedString
	}
	preview: {
		/**
		 * {index} of {total}
		 */
		position: (arg: { index: number, total: number }) => LocalizedString
		/**
		 * Zoom in
		 */
		zoomIn: () => LocalizedString
		/**
		 * Zoom out
		 */
		zoomOut: () => LocalizedString
		hints: {
			/**
			 * previous / next
			 */
			nav: () => LocalizedString
			/**
			 * zoom
			 */
			zoom: () => LocalizedString
			/**
			 * info panel
			 */
			info: () => LocalizedString
			/**
			 * close
			 */
			close: () => LocalizedString
		}
	}
	conflicts: {
		/**
		 * Resolve conflicts
		 */
		title: () => LocalizedString
		/**
		 * {count} {{item|items}} already {{exists|exist}} at the destination.
		 */
		body: (arg: { count: number }) => LocalizedString
		/**
		 * Overwrite all
		 */
		overwriteAll: () => LocalizedString
		/**
		 * Skip all
		 */
		skipAll: () => LocalizedString
		/**
		 * Overwrite
		 */
		overwrite: () => LocalizedString
		/**
		 * Skip
		 */
		skip: () => LocalizedString
	}
	search: {
		/**
		 * Search
		 */
		label: () => LocalizedString
		/**
		 * Search files, or type / for actions…
		 */
		placeholder: () => LocalizedString
		/**
		 * Quick actions
		 */
		quickActions: () => LocalizedString
		/**
		 * Recent
		 */
		recent: () => LocalizedString
		/**
		 * Searching…
		 */
		searching: () => LocalizedString
		/**
		 * Files · {count} {{match|matches}}
		 */
		matches: (arg: { count: number }) => LocalizedString
		/**
		 * No results for “{term}”
		 */
		noResults: (arg: { term: string }) => LocalizedString
		/**
		 * Try a different name or check the spelling.
		 */
		noResultsHint: () => LocalizedString
		/**
		 * open
		 */
		openHint: () => LocalizedString
		/**
		 * New file
		 */
		newFile: () => LocalizedString
		/**
		 * New folder
		 */
		newFolder: () => LocalizedString
		/**
		 * Upload…
		 */
		upload: () => LocalizedString
		/**
		 * Upload folder…
		 */
		uploadFolder: () => LocalizedString
		hints: {
			/**
			 * navigate
			 */
			navigate: () => LocalizedString
			/**
			 * open
			 */
			open: () => LocalizedString
			/**
			 * actions
			 */
			actions: () => LocalizedString
			/**
			 * close
			 */
			close: () => LocalizedString
		}
	}
	transfers: {
		/**
		 * Transfers
		 */
		title: () => LocalizedString
		/**
		 * Dismiss transfers
		 */
		dismiss: () => LocalizedString
		/**
		 * No transfers yet
		 */
		empty: () => LocalizedString
		/**
		 * Transferring {count} {{file|files}}
		 */
		transferring: (arg: { count: number }) => LocalizedString
		/**
		 * {count} complete
		 */
		complete: (arg: { count: number }) => LocalizedString
		/**
		 * Resolve conflicts
		 */
		resolveConflicts: () => LocalizedString
		/**
		 * Cancel transfer
		 */
		cancelTransfer: () => LocalizedString
		/**
		 * {count}s left
		 */
		etaSeconds: (arg: { count: number }) => LocalizedString
		/**
		 * about {count}m left
		 */
		etaMinutes: (arg: { count: number }) => LocalizedString
	}
	uploads: {
		/**
		 * Upload
		 */
		trigger: () => LocalizedString
		/**
		 * Upload to
		 */
		to: () => LocalizedString
		/**
		 * Minimize
		 */
		minimize: () => LocalizedString
		/**
		 * Expand uploads
		 */
		expand: () => LocalizedString
		/**
		 * Uploading {count} {{file|files}}
		 */
		uploading: (arg: { count: number }) => LocalizedString
		/**
		 * Upload complete
		 */
		complete: () => LocalizedString
		/**
		 * Upload drop zone
		 */
		dropzoneLabel: () => LocalizedString
		/**
		 * Drop files or folders here
		 */
		dropHere: () => LocalizedString
		/**
		 * Browse files
		 */
		browseFiles: () => LocalizedString
		/**
		 * Browse folder
		 */
		browseFolder: () => LocalizedString
		/**
		 * Up to 5 GB per file · resumable · chunked
		 */
		limits: () => LocalizedString
		/**
		 * QUEUE · {done} of {total} done
		 */
		queue: (arg: { done: number, total: number }) => LocalizedString
		/**
		 * Remove from queue
		 */
		removeFromQueue: () => LocalizedString
		/**
		 * Folder
		 */
		folder: () => LocalizedString
		/**
		 * Empty folder
		 */
		emptyFolder: () => LocalizedString
		/**
		 * {count}s left
		 */
		etaSeconds: (arg: { count: number }) => LocalizedString
		/**
		 * {count}m left
		 */
		etaMinutes: (arg: { count: number }) => LocalizedString
	}
	locales: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Português (Brasil)
		 */
		'pt-BR': () => LocalizedString
		/**
		 * Español
		 */
		es: () => LocalizedString
	}
	categories: {
		/**
		 * image
		 */
		image: () => LocalizedString
		/**
		 * video
		 */
		video: () => LocalizedString
		/**
		 * audio
		 */
		audio: () => LocalizedString
		/**
		 * pdf
		 */
		pdf: () => LocalizedString
		/**
		 * doc
		 */
		doc: () => LocalizedString
		/**
		 * sheet
		 */
		sheet: () => LocalizedString
		/**
		 * slide
		 */
		slide: () => LocalizedString
		/**
		 * code
		 */
		code: () => LocalizedString
		/**
		 * markup
		 */
		markup: () => LocalizedString
		/**
		 * data
		 */
		data: () => LocalizedString
		/**
		 * markdown
		 */
		markdown: () => LocalizedString
		/**
		 * archive
		 */
		archive: () => LocalizedString
		/**
		 * font
		 */
		font: () => LocalizedString
		/**
		 * binary
		 */
		binary: () => LocalizedString
		/**
		 * model
		 */
		model: () => LocalizedString
		/**
		 * text
		 */
		text: () => LocalizedString
		/**
		 * folder
		 */
		folder: () => LocalizedString
		/**
		 * file
		 */
		file: () => LocalizedString
	}
	kinds: {
		/**
		 * File
		 */
		file: () => LocalizedString
		/**
		 * Folder
		 */
		folder: () => LocalizedString
		/**
		 * {ext} file
		 */
		genericExt: (arg: { ext: string }) => LocalizedString
		/**
		 * JPEG image
		 */
		jpegImage: () => LocalizedString
		/**
		 * PNG image
		 */
		pngImage: () => LocalizedString
		/**
		 * GIF image
		 */
		gifImage: () => LocalizedString
		/**
		 * WebP image
		 */
		webpImage: () => LocalizedString
		/**
		 * SVG image
		 */
		svgImage: () => LocalizedString
		/**
		 * Bitmap image
		 */
		bitmapImage: () => LocalizedString
		/**
		 * TIFF image
		 */
		tiffImage: () => LocalizedString
		/**
		 * Icon
		 */
		icon: () => LocalizedString
		/**
		 * HEIC image
		 */
		heicImage: () => LocalizedString
		/**
		 * AVIF image
		 */
		avifImage: () => LocalizedString
		/**
		 * RAW image
		 */
		rawImage: () => LocalizedString
		/**
		 * MPEG-4 movie
		 */
		mpeg4Movie: () => LocalizedString
		/**
		 * QuickTime movie
		 */
		quicktimeMovie: () => LocalizedString
		/**
		 * Matroska video
		 */
		matroskaVideo: () => LocalizedString
		/**
		 * AVI video
		 */
		aviVideo: () => LocalizedString
		/**
		 * WebM video
		 */
		webmVideo: () => LocalizedString
		/**
		 * Flash video
		 */
		flashVideo: () => LocalizedString
		/**
		 * Windows Media video
		 */
		windowsMediaVideo: () => LocalizedString
		/**
		 * MPEG video
		 */
		mpegVideo: () => LocalizedString
		/**
		 * 3GP video
		 */
		threeGpVideo: () => LocalizedString
		/**
		 * MP3 audio
		 */
		mp3Audio: () => LocalizedString
		/**
		 * WAV audio
		 */
		wavAudio: () => LocalizedString
		/**
		 * FLAC audio
		 */
		flacAudio: () => LocalizedString
		/**
		 * AAC audio
		 */
		aacAudio: () => LocalizedString
		/**
		 * Ogg audio
		 */
		oggAudio: () => LocalizedString
		/**
		 * MPEG-4 audio
		 */
		mpeg4Audio: () => LocalizedString
		/**
		 * Windows Media audio
		 */
		windowsMediaAudio: () => LocalizedString
		/**
		 * Opus audio
		 */
		opusAudio: () => LocalizedString
		/**
		 * AIFF audio
		 */
		aiffAudio: () => LocalizedString
		/**
		 * PDF document
		 */
		pdfDocument: () => LocalizedString
		/**
		 * Word document
		 */
		wordDocument: () => LocalizedString
		/**
		 * OpenDocument text
		 */
		openDocumentText: () => LocalizedString
		/**
		 * Rich text
		 */
		richText: () => LocalizedString
		/**
		 * Plain text
		 */
		plainText: () => LocalizedString
		/**
		 * Excel spreadsheet
		 */
		excelSpreadsheet: () => LocalizedString
		/**
		 * OpenDocument sheet
		 */
		openDocumentSheet: () => LocalizedString
		/**
		 * PowerPoint presentation
		 */
		powerpointPresentation: () => LocalizedString
		/**
		 * OpenDocument slides
		 */
		openDocumentSlides: () => LocalizedString
		/**
		 * EPUB book
		 */
		epubBook: () => LocalizedString
		/**
		 * Markdown
		 */
		markdown: () => LocalizedString
		/**
		 * MDX
		 */
		mdx: () => LocalizedString
		/**
		 * JavaScript
		 */
		javascript: () => LocalizedString
		/**
		 * JavaScript React
		 */
		javascriptReact: () => LocalizedString
		/**
		 * TypeScript
		 */
		typescript: () => LocalizedString
		/**
		 * TypeScript React
		 */
		typescriptReact: () => LocalizedString
		/**
		 * Go source
		 */
		goSource: () => LocalizedString
		/**
		 * Rust source
		 */
		rustSource: () => LocalizedString
		/**
		 * Python source
		 */
		pythonSource: () => LocalizedString
		/**
		 * Ruby source
		 */
		rubySource: () => LocalizedString
		/**
		 * Java source
		 */
		javaSource: () => LocalizedString
		/**
		 * Kotlin source
		 */
		kotlinSource: () => LocalizedString
		/**
		 * C source
		 */
		cSource: () => LocalizedString
		/**
		 * C header
		 */
		cHeader: () => LocalizedString
		/**
		 * C++ source
		 */
		cppSource: () => LocalizedString
		/**
		 * C++ header
		 */
		cppHeader: () => LocalizedString
		/**
		 * C# source
		 */
		csharpSource: () => LocalizedString
		/**
		 * PHP source
		 */
		phpSource: () => LocalizedString
		/**
		 * Swift source
		 */
		swiftSource: () => LocalizedString
		/**
		 * Shell script
		 */
		shellScript: () => LocalizedString
		/**
		 * SQL
		 */
		sql: () => LocalizedString
		/**
		 * Lua source
		 */
		luaSource: () => LocalizedString
		/**
		 * R source
		 */
		rSource: () => LocalizedString
		/**
		 * Dart source
		 */
		dartSource: () => LocalizedString
		/**
		 * Vue component
		 */
		vueComponent: () => LocalizedString
		/**
		 * Svelte component
		 */
		svelteComponent: () => LocalizedString
		/**
		 * HTML document
		 */
		htmlDocument: () => LocalizedString
		/**
		 * Stylesheet
		 */
		stylesheet: () => LocalizedString
		/**
		 * Sass stylesheet
		 */
		sassStylesheet: () => LocalizedString
		/**
		 * Less stylesheet
		 */
		lessStylesheet: () => LocalizedString
		/**
		 * JSON
		 */
		json: () => LocalizedString
		/**
		 * YAML
		 */
		yaml: () => LocalizedString
		/**
		 * TOML
		 */
		toml: () => LocalizedString
		/**
		 * XML
		 */
		xml: () => LocalizedString
		/**
		 * CSV
		 */
		csv: () => LocalizedString
		/**
		 * TSV
		 */
		tsv: () => LocalizedString
		/**
		 * INI config
		 */
		iniConfig: () => LocalizedString
		/**
		 * Env file
		 */
		envFile: () => LocalizedString
		/**
		 * Config
		 */
		config: () => LocalizedString
		/**
		 * Archive
		 */
		archive: () => LocalizedString
		/**
		 * Executable
		 */
		executable: () => LocalizedString
		/**
		 * Debian package
		 */
		debianPackage: () => LocalizedString
		/**
		 * RPM package
		 */
		rpmPackage: () => LocalizedString
		/**
		 * Disk image
		 */
		diskImage: () => LocalizedString
		/**
		 * Log file
		 */
		logFile: () => LocalizedString
		/**
		 * STL model
		 */
		stlModel: () => LocalizedString
		/**
		 * OBJ model
		 */
		objModel: () => LocalizedString
		/**
		 * PLY model
		 */
		plyModel: () => LocalizedString
		/**
		 * glTF model
		 */
		gltfModel: () => LocalizedString
		/**
		 * Font
		 */
		font: () => LocalizedString
	}
}

export type Formatters = {
	n: (value: number) => unknown
}
